version: '3.8'

services:
  parcel-tracking-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: parcel-tracking-tool:latest
    container_name: parcel-tracking-container
    ports:
      - "8080:8080"
    environment:
      # JVM options can be overridden here
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC
      # Spring profiles
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - parcel-network

networks:
  parcel-network:
    driver: bridge
