spring:
  application:
    name: parcel-tracking-tool
  
  # H2 Database Configuration for testing
  # TODO: Change to MySQL/Postgres
  datasource:
    url: jdbc:h2:mem:parceldb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console (for development/testing)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

# Server Configuration
server:
  port: 8080

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging Configuration
logging:
  level:
    com.hotel.parceltracking: DEBUG
    org.springframework.web: DEBUG

# Actuator configuration for Docker health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true